# Generated by Django 4.0.4 on 2022-06-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_post_options_post_amount_likes_post_liked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='marked_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_profiles', to='account.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_authors', to='account.profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProfileMark',
        ),
    ]
